version: '3.8'

services:
  api:
    build: ./ATHM-backend  
    container_name: athm-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://abdulrafay:rafay@cluster0.wlcpcro.mongodb.net/ATHM_DB?retryWrites=true&w=majority
      - JWT_SECRET=your_super_secret_key
      - NODE_ENV=production

  client:
    build: ./ATHM-frontend  
    container_name: athm-frontend
    ports:
      - "5173:5173"
    depends_on:
      - api